### ISSUE TITLE
/admin.php?/cp/addons/settings/emoji_support/convert:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by mark-chief** [EllisLab/Emoji-Support#1]
I am getting this error in the console when trying to install this addon.

EE v 3.5.2

`/admin.php?/cp/addons/settings/emoji_support/convert:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

**Comment by mark-chief** [comment]
`access.php?S=0&D=cp&C=javascript&M=combo_load&package=emoji_support:convert&v=1540896050:128 POST https://www.domain.com/access.php?/cp/addons/settings/emoji_support/convert 500 (Internal Server Error)`

**Comment by kevincupp** [comment]
Handled in Slack
